// Generated by gencpp from file robot_main/sensor_flag.msg
// DO NOT EDIT!


#ifndef ROBOT_MAIN_MESSAGE_SENSOR_FLAG_H
#define ROBOT_MAIN_MESSAGE_SENSOR_FLAG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_main
{
template <class ContainerAllocator>
struct sensor_flag_
{
  typedef sensor_flag_<ContainerAllocator> Type;

  sensor_flag_()
    : flag(0)  {
    }
  sensor_flag_(const ContainerAllocator& _alloc)
    : flag(0)  {
  (void)_alloc;
    }



   typedef int32_t _flag_type;
  _flag_type flag;





  typedef boost::shared_ptr< ::robot_main::sensor_flag_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_main::sensor_flag_<ContainerAllocator> const> ConstPtr;

}; // struct sensor_flag_

typedef ::robot_main::sensor_flag_<std::allocator<void> > sensor_flag;

typedef boost::shared_ptr< ::robot_main::sensor_flag > sensor_flagPtr;
typedef boost::shared_ptr< ::robot_main::sensor_flag const> sensor_flagConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_main::sensor_flag_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_main::sensor_flag_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_main::sensor_flag_<ContainerAllocator1> & lhs, const ::robot_main::sensor_flag_<ContainerAllocator2> & rhs)
{
  return lhs.flag == rhs.flag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_main::sensor_flag_<ContainerAllocator1> & lhs, const ::robot_main::sensor_flag_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_main

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_main::sensor_flag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_main::sensor_flag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_main::sensor_flag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_main::sensor_flag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_main::sensor_flag_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_main::sensor_flag_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_main::sensor_flag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aa0dbc5596ec12974ea3a17a045b36e0";
  }

  static const char* value(const ::robot_main::sensor_flag_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaa0dbc5596ec1297ULL;
  static const uint64_t static_value2 = 0x4ea3a17a045b36e0ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_main::sensor_flag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_main/sensor_flag";
  }

  static const char* value(const ::robot_main::sensor_flag_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_main::sensor_flag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 flag\n"
;
  }

  static const char* value(const ::robot_main::sensor_flag_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_main::sensor_flag_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sensor_flag_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_main::sensor_flag_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_main::sensor_flag_<ContainerAllocator>& v)
  {
    s << indent << "flag: ";
    Printer<int32_t>::stream(s, indent + "  ", v.flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MAIN_MESSAGE_SENSOR_FLAG_H
