// Generated by gencpp from file communication_demo/mess.msg
// DO NOT EDIT!


#ifndef COMMUNICATION_DEMO_MESSAGE_MESS_H
#define COMMUNICATION_DEMO_MESSAGE_MESS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace communication_demo
{
template <class ContainerAllocator>
struct mess_
{
  typedef mess_<ContainerAllocator> Type;

  mess_()
    : count(0)  {
    }
  mess_(const ContainerAllocator& _alloc)
    : count(0)  {
  (void)_alloc;
    }



   typedef int64_t _count_type;
  _count_type count;





  typedef boost::shared_ptr< ::communication_demo::mess_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::communication_demo::mess_<ContainerAllocator> const> ConstPtr;

}; // struct mess_

typedef ::communication_demo::mess_<std::allocator<void> > mess;

typedef boost::shared_ptr< ::communication_demo::mess > messPtr;
typedef boost::shared_ptr< ::communication_demo::mess const> messConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::communication_demo::mess_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::communication_demo::mess_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::communication_demo::mess_<ContainerAllocator1> & lhs, const ::communication_demo::mess_<ContainerAllocator2> & rhs)
{
  return lhs.count == rhs.count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::communication_demo::mess_<ContainerAllocator1> & lhs, const ::communication_demo::mess_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace communication_demo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::communication_demo::mess_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::communication_demo::mess_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::communication_demo::mess_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::communication_demo::mess_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::communication_demo::mess_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::communication_demo::mess_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::communication_demo::mess_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8dbac33d2eb67bfeeedd516d65fec846";
  }

  static const char* value(const ::communication_demo::mess_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8dbac33d2eb67bfeULL;
  static const uint64_t static_value2 = 0xeedd516d65fec846ULL;
};

template<class ContainerAllocator>
struct DataType< ::communication_demo::mess_<ContainerAllocator> >
{
  static const char* value()
  {
    return "communication_demo/mess";
  }

  static const char* value(const ::communication_demo::mess_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::communication_demo::mess_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 count\n"
;
  }

  static const char* value(const ::communication_demo::mess_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::communication_demo::mess_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mess_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::communication_demo::mess_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::communication_demo::mess_<ContainerAllocator>& v)
  {
    s << indent << "count: ";
    Printer<int64_t>::stream(s, indent + "  ", v.count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMUNICATION_DEMO_MESSAGE_MESS_H
